export default function (err) {
  console.log("caught!", { err });
}
